version: "3"
services:
  database:
    # restart docker container when there will be a crash
    restart: always
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    # instead of environment let's use the env file
    env_file: .env
  web:
    restart: always
    image: ghcr.io/mykurts/rails_app:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 1598 -b '0.0.0.0'"
    env_file: .env

    volumes:
      - ./log:/app/log # store logs in `log` directory
    ports:
      - 1598:1598
    depends_on:
      - database
volumes:
  db_data: